// tailwind.config.js
module.exports = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "outline-variant": "#c4c6cf",
                "on-primary": "#ffffff",
                "tertiary-fixed-dim": "#c4c7c9",
                "tertiary-container": "#333638",
                "surface-container-lowest": "#ffffff",
                "surface-bright": "#f8f9ff",
                "tertiary-fixed": "#e0e3e5",
                outline: "#74777f",
                "on-surface-variant": "#43474e",
                "error-container": "#ffdad6",
                "surface-container-highest": "#d3e4fe",
                "inverse-primary": "#adc7f7",
                surface: "#f8f9ff",
                "on-error": "#ffffff",
                "on-secondary-container": "#745c00",
                "primary-container": "#1a365d",
                "on-error-container": "#93000a",
                "primary-fixed": "#d6e3ff",
                "secondary-fixed-dim": "#e9c349",
                "surface-container": "#e5eeff",
                primary: "#002045",
                "inverse-surface": "#213145",
                "primary-fixed-dim": "#adc7f7",
                "on-background": "#0b1c30",
                "on-tertiary": "#ffffff",
                "on-secondary-fixed-variant": "#574500",
                "surface-container-high": "#dce9ff",
                "secondary-container": "#fed65b",
                "on-tertiary-fixed-variant": "#444749",
                "on-primary-fixed": "#001b3c",
                "on-surface": "#0b1c30",
                "on-secondary-fixed": "#241a00",
                "surface-variant": "#d3e4fe",
                background: "#f8f9ff",
                "on-primary-fixed-variant": "#2d476f",
                tertiary: "#1d2123",
                "surface-container-low": "#eff4ff",
                "on-tertiary-fixed": "#191c1e",
                "on-primary-container": "#86a0cd",
                "surface-tint": "#455f88",
                secondary: "#735c00",
                "on-tertiary-container": "#9c9fa1",
                "secondary-fixed": "#ffe088",
                "surface-dim": "#cbdbf5",
                error: "#ba1a1a",
                "on-secondary": "#ffffff",
                "inverse-on-surface": "#eaf1ff",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            spacing: {
                "unit-1": "0.25rem",
                "unit-4": "1rem",
                "unit-6": "1.5rem",
                "unit-8": "2rem",
                "unit-2": "0.5rem",
                gutter: "24px",
                "container-max": "1280px",
                "unit-12": "3rem",
                "margin-mobile": "16px",
                base: "4px",
            },
            fontFamily: {
                "label-md": ["Inter"],
                "body-md": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "label-sm": ["Inter"],
                "headline-xl": ["Inter"],
                "headline-lg": ["Inter"],
                "headline-md": ["Inter"],
                "body-lg": ["Inter"],
            },
            fontSize: {
                "label-md": [
                    "14px",
                    {
                        lineHeight: "20px",
                        letterSpacing: "0.01em",
                        fontWeight: "500",
                    },
                ],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "headline-lg-mobile": [
                    "24px",
                    { lineHeight: "32px", fontWeight: "600" },
                ],
                "label-sm": [
                    "12px",
                    {
                        lineHeight: "16px",
                        letterSpacing: "0.05em",
                        fontWeight: "600",
                    },
                ],
                "headline-xl": [
                    "40px",
                    {
                        lineHeight: "48px",
                        letterSpacing: "-0.02em",
                        fontWeight: "700",
                    },
                ],
                "headline-lg": [
                    "32px",
                    {
                        lineHeight: "40px",
                        letterSpacing: "-0.02em",
                        fontWeight: "600",
                    },
                ],
                "headline-md": [
                    "24px",
                    { lineHeight: "32px", fontWeight: "600" },
                ],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
            },
        },
    },
};
